# Arrays

In [2]:
import numpy as np
a = np.array([1, 2, 3, 4.0])  # Create a rank 1 array
print type(a), a.shape, a[0], a[1], a[2]
a[0] = 5                 # Change an element of the array
print a
print '---------'
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print b
print b.shape                   
print b[0, 0], b[0, 2], b[1, 0]

<type 'numpy.ndarray'> (4L,) 1.0 2.0 3.0
[ 5.  2.  3.  4.]
---------
[[1 2 3]
 [4 5 6]]
(2L, 3L)
1 3 4


In [3]:
a = np.zeros((2,2))  # Create an array of all zeros
print a
b = np.ones((2,1))   # Create an array of all ones
print b
c = np.full((2,3), 7) # Create a constant array
print c
d = np.eye(4)        # Create a 2x2 identity matrix
print d
e = np.random.random((2,2)) # Create an array filled with random values
print e

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.]
 [ 1.]]
[[7 7 7]
 [7 7 7]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 0.08494777  0.69064717]
 [ 0.82128963  0.71156714]]


# Array indexing

In [14]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print a
print b

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [15]:
print a[0, 1]  
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print a[0, 1]
print a
print '-------------'
c = b[:]
print c
print '-------------'
c[1,1] = 55
print a

2
77
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-------------
[[77  3]
 [ 6  7]]
-------------
[[ 1 77  3  4]
 [ 5  6 55  8]
 [ 9 10 11 12]]


what if I want to work on copies of A 
1. A is appearing to be changing as we operate on the copies 
2. I lose the original matrix if I operate on slices of a given matrix

In [16]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print a

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print row_r1, row_r1.shape 
print row_r2, row_r2.shape
print row_r3, row_r3.shape

[5 6 7 8] (4L,)
[[5 6 7 8]] (1L, 4L)
[[5 6 7 8]] (1L, 4L)


1. What is 'L' ?
2. Is row_r1 an array and other two matrix ? , is that why we have 2 sq brackets in 2nd and 3rd o/p 
--> 2 and 3 are using a slice of a, that is why 2 brackets; 1 itself is a slice

In [18]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print col_r1, col_r1.shape
print 
print col_r2, col_r2.shape

[ 2  6 10] (3L,)

[[ 2]
 [ 6]
 [10]] (3L, 1L)


1. why are we getting a transpose in 1st o/p ? --> just a slice 


In [24]:
M = np.array([[1,2], [3, 4], [5, 6]])
print M

print

print M[0,1]
print M[[0,1]]

print
print M[:,[0,1]]
print M[[0,1],]
print

# An example of integer array indexing.
# The returned array will have shape (3,) and 
print M[[0, 1, 2], [0, 1, 0]]

print
# The above example of integer array indexing is equivalent to this:
print np.array([M[0, 0], M[1, 1], M[2, 0]])

[[1 2]
 [3 4]
 [5 6]]

2
[[1 2]
 [3 4]]

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]

[1 4 5]
[1 4 5]


In [25]:
print a

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
#diagonal elements
k= a[[0,1,2],[0,1,2]]
print k

[ 1  6 11]


In [28]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print a
print
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print a[np.arange(4), b]  # Prints "[ 1  6  7 11]"
print
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print a


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[ 1  6  7 11]

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [30]:
#Boolean array indexing
A = np.array([[1,2], [3, 4], [5, 6]])
print A
bool_idx = (A > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print bool_idx
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print A[bool_idx]

# We can do all of the above in a single concise statement:
print A[A > 2]

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


Q. How to find the indices of the elements satisfying a given condition (bool_idx in this case)

# Datatypes

In [31]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print x.dtype, y.dtype, z.dtype

int32 float64 int64


# array math

In [50]:
V = np.array([[1,2],[8,9]])
T = np.array([[3,4],[5,6]])

print V 
print T
print np.add(V,T)
#print (V+T) - np.add(V,T)
print
print np.subtract(V,T)
print V-T
print
print np.multiply(V,T)
print V*T
print
print np.dot(V,T)
print V.T

print V.dot(T)
print
print np.divide(V,T)
print V/T
print
print np.sqrt(V)

[[1 2]
 [8 9]]
[[3 4]
 [5 6]]
[[ 4  6]
 [13 15]]

[[-2 -2]
 [ 3  3]]
[[-2 -2]
 [ 3  3]]

[[ 3  8]
 [40 54]]
[[ 3  8]
 [40 54]]

[[13 16]
 [69 86]]
[[1 8]
 [2 9]]
[[13 16]
 [69 86]]

[[0 0]
 [1 1]]
[[0 0]
 [1 1]]

[[ 1.          1.41421356]
 [ 2.82842712  3.        ]]


note , for V.T it gave a transpose of V coz dotT is the operation that we use for transpose. 

In [53]:
x = np.array([[1,2],[3,4]])

print x
print x.T

print np.sum(x)  # Compute sum of all elements; prints "10"
print np.sum(x, axis=0)  # Compute sum of each column; prints "[4 6]"
print np.sum(x, axis=1)  # Compute sum of each row; prints "[3 7]"
print np.sum(x,axis=3)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
10
[4 6]
[3 7]


AxisError: axis 3 is out of bounds for array of dimension 2

# Broadcasting

In [59]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print y
print

vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print vv                 # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

print 

y = x + vv  # Add x and vv elementwise
print y

print
m = x+v
print m

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Broadcasting two arrays together follows these rules:
1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

In [63]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
print v
print
print np.reshape(v, (3, 1)) * w
print v

[1 2 3]

[[ 4  5]
 [ 8 10]
 [12 15]]
[1 2 3]


In [64]:
x = np.array([[1,2,3], [4,5,6]])
print x + v

print (x.T + w).T

[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]


In [65]:
print x + np.reshape(w, (2, 1))

[[ 5  6  7]
 [ 9 10 11]]


In [66]:
print x * 2

[[ 2  4  6]
 [ 8 10 12]]
